version: '3'
services:
  nodejs-server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'backendtask'
      MYSQL_USER: 'task_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 30
      timeout: 20s
      start_period: 10s
